# This Source Code Form is licensed MPL-2.0: http://mozilla.org/MPL/2.0
#
# http://docs.travis-ci.com/user/customizing-the-build/
# http://lint.travis-ci.org/

os: linux
dist: trusty
sudo: required
services: docker
language: c

env:
  global:
    #- http_proxy="http://example.com"
    - INTENT="package" # default intent
  matrix:
    # package: build packages for distribution $DIST
    - DIST="ubuntu:wily"
    - DIST="debian:jessie"
    - DIST="debian:testing"
    - DIST="ubuntu:xenial"
    # distcheck: succeed in 'make distcheck'
    - INTENT="distcheck" DIST="ubuntu:wily"
    # clangbuild: succeed in using clang++ for builds
    - INTENT="clangbuild" DIST="ubuntu:wily"
matrix:
  allow_failures:
    - env: DIST="debian:testing"
    - env: INTENT="distcheck" DIST="ubuntu:wily"
  fast_finish: true

before_install:
  - travis_retry git fetch --unshallow # git describe requires complete history
  # Build variable setup; example: DIST=debian:jessie DISTRELEASE=jessie RC={deb|devel}
  - true &&
    DISTRELEASE="${DIST#*:}" &&
    BUILDID=`misc/mkbuildid.sh -p` && { test "$BUILDID" = "${BUILDID%-*}" && RC=deb || RC=devel ; } &&
    BEASTAPTSOURCE="deb [trusted=yes] https://dl.bintray.com/beast-team/$RC $DISTRELEASE main" &&
    export DISTRELEASE BEASTAPTSOURCE BUILDID RC &&
    echo "INTENT=$INTENT DIST=$DIST DISTRELEASE=$DISTRELEASE BUILDID=$BUILDID RC=$RC BEASTAPTSOURCE='$BEASTAPTSOURCE'"
  # Sample environment
  - uname -a
  - cat /etc/os-release
  - pwd
  - free -tm
  - make --version
  - python --version
  - $CC --version

install:
  # Build inside docker container
  - misc/dockerbuild.sh $DIST $INTENT

script:
  # Upload packages
  - ([ $INTENT = package ] || exit 0 && docker run -ti --rm rapicorn /bin/bash -c \
        "export BINTRAY_APITOKEN=$BINTRAY_APITOKEN && ls -al .. && misc/bintrayup.sh $DIST beast-team@$RC/rapicorn ../*.deb")
  # Test package installation from remote location
  - ([ $INTENT = package ] || exit 0 && sleep 60 && travis_retry docker run -ti --rm rapicorn /bin/bash -c \
        "set -x && retry apt-get -y install apt-transport-https ca-certificates &&
        echo '$BEASTAPTSOURCE' | tee /etc/apt/sources.list.d/beast-team.list &&
        retry apt-get update && retry apt-get -y install rapicorn")
  - docker ps -a

after_success:
  - echo "Done, all OK!"

notifications:
  irc:
    channels:
      - "irc.gimp.org#beast"
    on_success: always
    on_failure: always
    skip_join: true
  email: false
    #recipients:
    #  - rapicorn@googlegroups.com
    #on_success: never
    #on_failure: change
