# This Source Code Form is licensed MPL-2.0: http://mozilla.org/MPL/2.0
#
# http://docs.travis-ci.com/user/customizing-the-build/
# http://lint.travis-ci.org/

os: linux
dist: trusty
sudo: required
services: docker
language: generic

env:
  # INTENT: gccbuild clangbuild package bintrayup
  matrix:
    - DIST="ubuntu:wily"     INTENT="gccbuild,package,bintrayup"
    - DIST="ubuntu:xenial"   INTENT="gccbuild,package,bintrayup,distcheck"
    - DIST="debian:jessie"   INTENT="gccbuild,package,bintrayup"
    # test upcoming releases and get new compiler warnings
    - DIST="debian:stretch"  INTENT="gccbuild,package,bintrayup"
    - DIST="ubuntu:zesty"    INTENT="gccbuild"
    - DIST="ubuntu:zesty"    INTENT="clangbuild"
    - DIST="debian:unstable" INTENT="gccbuild"
    - DIST="debian:unstable" INTENT="clangbuild"
matrix:
  allow_failures:
    - env: DIST="debian:stretch"  INTENT="gccbuild,package,bintrayup"
    - env: DIST="ubuntu:zesty"    INTENT="gccbuild"
    - env: DIST="ubuntu:zesty"    INTENT="clangbuild"
    - env: DIST="debian:unstable" INTENT="gccbuild"
    - env: DIST="debian:unstable" INTENT="clangbuild"
  fast_finish: true

before_install:
  # Show build setup
  - echo "INTENT=$INTENT DIST=$DIST"
  - uname -a
  - cat /etc/os-release
  - pwd
  - free -tm
  - python --version

install:
  # git describe requires complete history
  - travis_retry git fetch --unshallow

script:
  # Build inside docker container
  - misc/dockerbuild.sh "$DIST" "$INTENT"
  - docker ps -a

after_success:
  - echo "OK, all done."

notifications:
  irc:
    channels:
      - "irc.gimp.org#beast"
    on_success: always
    on_failure: always
    skip_join: true
  email: false
    #recipients:
    #  - rapicorn@googlegroups.com
    #on_success: never
    #on_failure: change
