# This Source Code Form is licensed MPL-2.0: http://mozilla.org/MPL/2.0
#
# http://docs.travis-ci.com/user/customizing-the-build/
# http://lint.travis-ci.org/

os: linux
dist: trusty
sudo: required
services: docker
language: generic

env:
  global:
    - INTENT="package,bintrayup" # default
  matrix:
    # package: build packages for distribution $DIST
    - DIST="ubuntu:wily"
    - DIST="debian:jessie"
    - DIST="debian:testing"
    - DIST="ubuntu:xenial"
    - DIST="ubuntu:yakkety"
    - DIST="ubuntu:yakkety" INTENT="clangbuild,distcheck"
matrix:
  allow_failures:
    - env: DIST="debian:testing"
    - env: DIST="ubuntu:xenial"
    - env: DIST="ubuntu:yakkety"
  fast_finish: true

before_install:
  # Show build setup
  - echo "INTENT=$INTENT DIST=$DIST"
  - uname -a
  - cat /etc/os-release
  - pwd
  - free -tm
  - python --version

install:
  # git describe requires complete history
  - travis_retry git fetch --unshallow

script:
  # Build inside docker container
  - misc/dockerbuild.sh "$DIST" "$INTENT"
  - docker ps -a

after_success:
  - echo "OK, all done."

notifications:
  irc:
    channels:
      - "irc.gimp.org#beast"
    on_success: always
    on_failure: always
    skip_join: true
  email: false
    #recipients:
    #  - rapicorn@googlegroups.com
    #on_success: never
    #on_failure: change
